// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvMqXmKgMXoxGO2qESE4uz6MxSNIC9SQ',
    appId: '1:176596059403:web:255f1c6cd8534861e80e0e',
    messagingSenderId: '176596059403',
    projectId: 'quiz-flutter-46c9a',
    authDomain: 'quiz-flutter-46c9a.firebaseapp.com',
    storageBucket: 'quiz-flutter-46c9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZL_RghLWjY3BIkpYfxlxG8NzU48d4oo',
    appId: '1:176596059403:android:d0c303420ba3e1b9e80e0e',
    messagingSenderId: '176596059403',
    projectId: 'quiz-flutter-46c9a',
    storageBucket: 'quiz-flutter-46c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0zf-6gcT48k8GkqnHiLaJ7tR6dfiU-s',
    appId: '1:176596059403:ios:fcacd19186936a2ee80e0e',
    messagingSenderId: '176596059403',
    projectId: 'quiz-flutter-46c9a',
    storageBucket: 'quiz-flutter-46c9a.firebasestorage.app',
    iosBundleId: 'com.example.quizFlutter',
  );
}
